### PR TITLE
WIP: Build as noarch: python package

### PR DESCRIPTION
**Pull request by jjhelmus**

### CODE REVIEW

**Comment by jjhelmus** [comment]
Feedstock maintainer, please do not merge this yet.  It is a test to see if `noarch: python` might make sense for conda-forge.  This feedstock just happened to be a convenient package to test the idea on.

For those interested.  `noarch: python` packages were [officially support in conda 4.3](https://www.continuum.io/blog/developer-blog/announcing-general-availability-conda-4-3).  They could allow a single conda package to be built which works on all platforms and python versions!  The package in question but be "fully universal", they callnot have OS or Python version specific build rules or dependencies.

**Comment by ocefpaf** [comment]
@jjhelmus looks quite simple. Maybe we should add  a custom entry in the recipe that `conda-smithy` could read and render the recipe that way.

**Comment by chohner** [comment]
Seems like Circle runs fine, what's the status on this?

**Comment by jakirkham** [comment]
Should this be updated or closed?

**Comment by jjhelmus** [comment]
Yes, closing this.  

`noarch: python` can be added at the next release or at the maintainers leisure using the standard re-rending process.

**Pull request closed without merging**
